version: '3.7'

services:
  edge-gateway:
    image: envoyproxy/envoy-alpine:v1.16.1
    volumes:
      - ./edge-gateway/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - service-a-sidecar
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'edge-gateway' --service-node 'edge-gateway'

  service-a-sidecar:
    image: envoyproxy/envoy-alpine:v1.16.1
    volumes:
      - ./service-a/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8786:8786
      - 8788:8788
    depends_on:
      - service-a
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml  -l info --service-cluster 'service-a' --service-node 'service-a'

  service-a:
    build: service-a/
    ports:
      - 8081:8081

  service-b-sidecar:
    image: envoyproxy/envoy-alpine:v1.16.1
    volumes:
      - ./service-b/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8789:8789
    depends_on:
      - service-b
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-b' --service-node 'service-b'

  service-b:
    build: service-b/
    ports:
      - 8082:8082

  service-c-sidecar:
    image: envoyproxy/envoy-alpine:v1.16.1
    volumes:
      - ./service-c/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - 8790:8790
    depends_on:
      - service-c
    command: /usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-c' --service-node 'service-c'   

  service-c:
    build: service-c/
    ports:
      - 8083:8083  
